# Generated by Django 2.0.2 on 2018-02-27 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jplag', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='checkre',
            new_name='checker',
        ),
    ]
